# Script generated by the distribute setup command

import setuptools


setuptools.setup(
	name = "{{ component['name'] }}",
	version = "{{ configuration['project_version']['full'] }}",
	description = "{{ component['description'] }}",
	author = "{{ configuration['author'] }}",
	author_email = "{{ configuration['author_email'] }}",
	url = "{{ configuration['project_url'] }}",

	packages = [
		{% for package in component['packages'] %}
		"{{ package }}",
		{% endfor %}
	],

	install_requires = [
		{% for dependency in component['dependencies'] %}
		"{{ dependency }}",
		{% endfor %}
	],
)
